# Generated by Django 3.2.7 on 2022-04-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220416_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='track_number',
            field=models.CharField(blank=True, default='b/n', max_length=30, null=True, verbose_name='Track number'),
        ),
    ]
