# Generated by Django 3.2.7 on 2022-04-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_letter_track_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='track_number',
            field=models.CharField(default='b/n', max_length=30, verbose_name='Track number'),
        ),
    ]
