# Generated by Django 3.2.7 on 2021-09-21 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('account_number', models.CharField(max_length=50, verbose_name='Номер счета')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название банка')),
                ('extra_parameters', models.CharField(max_length=100, verbose_name='Дополнительные параметры')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='Валюта')),
                ('chosen_by_default', models.BooleanField(blank=True, default=False, verbose_name='Выбрать по умолчанию')),
            ],
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания ноты')),
                ('issue_date', models.DateField(verbose_name='Дата выставления')),
                ('payment_period', models.PositiveSmallIntegerField(default=60, verbose_name='Срок оплаты')),
                ('payment_deadline_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('total_amount', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Сумма к оплате')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Валюта')),
                ('is_paid', models.BooleanField(blank=True, default=False, verbose_name='Оплачено')),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='debit_note.bankaccount', verbose_name='Банковский счёт')),
                ('company_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.maincompany', verbose_name='Выставил(компания)')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выставил(сотрудник)')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('chosen_by_default', models.BooleanField(blank=True, default=False, verbose_name='Выбрать по умолчанию')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фирмы')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='Налоговый номер')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Сумма')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debit_note.currency', verbose_name='Валюта')),
                ('debit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='debit_note.debitnote', verbose_name='Позиция')),
            ],
        ),
        migrations.CreateModel(
            name='IssuerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фирмы')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='Налоговый номер')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('chosen_by_default', models.BooleanField(blank=True, default=False, verbose_name='Выбрать по умолчанию')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='debitnote',
            name='issuer_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='debit_note.issuercompany', verbose_name='Предоставитель услуги'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='debit_note.paymentmethod', verbose_name='Форма платежа'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='purchaser_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='debit_note.purchasercompany', verbose_name='Плательщик'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debit_note.issuercompany', verbose_name='Владелец счёта'),
        ),
    ]
