# Generated by Django 3.2.7 on 2021-09-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210921_1310'),
        ('debit_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuercompany',
            name='company_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.maincompany', verbose_name='Выставил(компания)'),
        ),
        migrations.AddField(
            model_name='purchasercompany',
            name='company_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.maincompany', verbose_name='Выставил(компания)'),
        ),
    ]
