# Generated by Django 3.2.7 on 2021-09-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210921_1310'),
        ('debit_note', '0003_auto_20210921_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debit_note.issuercompany', verbose_name='Владелец счёта'),
        ),
        migrations.AlterField(
            model_name='issuercompany',
            name='company_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.maincompany', verbose_name='Создал(компания)'),
        ),
        migrations.AlterField(
            model_name='purchasercompany',
            name='company_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.maincompany', verbose_name='Создал(компания)'),
        ),
    ]
