# Generated by Django 3.2.7 on 2021-09-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210921_1310'),
        ('debit_note', '0004_auto_20210922_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='company_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.maincompany', verbose_name='Создал(компания)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='company_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.maincompany', verbose_name='Создал(компания)'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='debit_note.issuercompany', verbose_name='Владелец счёта'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='company_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.maincompany', verbose_name='Создал(компания)'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='total_amount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False, verbose_name='Сумма к оплате'),
        ),
    ]
