# Generated by Django 3.2.7 on 2021-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit_note', '0007_alter_issuercompany_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasercompany',
            name='tax_id',
            field=models.CharField(max_length=50, verbose_name='Налоговый номер'),
        ),
    ]
