# Generated by Django 3.2.7 on 2022-04-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit_note', '0008_alter_purchasercompany_tax_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debitnote',
            options={'ordering': ('company_creator', 'id')},
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='payment_deadline_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Дата оплаты'),
        ),
    ]
